"""empty message

Revision ID: 190327547c72
Revises: e6333fa38da7
Create Date: 2023-07-05 15:07:47.874500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190327547c72'
down_revision = 'e6333fa38da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
