"""empty message

Revision ID: 453d88c8440c
Revises: dd383759b091
Create Date: 2024-11-16 17:09:51.506633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453d88c8440c'
down_revision = 'dd383759b091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wastebins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seenby', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wastebins', schema=None) as batch_op:
        batch_op.drop_column('seenby')

    # ### end Alembic commands ###
