"""empty message

Revision ID: dd383759b091
Revises: 
Create Date: 2024-11-16 15:27:28.460671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd383759b091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wastebins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binId', sa.String(length=50), nullable=True),
    sa.Column('lon', sa.String(length=28), nullable=True),
    sa.Column('lat', sa.String(length=28), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('binnotifys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('bId', sa.Integer(), nullable=True),
    sa.Column('binDate', sa.String(length=40), nullable=True),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bId'], ['wastebins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binnotifys')
    op.drop_table('wastebins')
    # ### end Alembic commands ###
