"""empty message

Revision ID: e6333fa38da7
Revises: a46d7a6cd3ab
Create Date: 2023-06-30 21:42:47.599280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6333fa38da7'
down_revision = 'a46d7a6cd3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('contact', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('noOfAttemptFailed', sa.Integer(), nullable=True),
    sa.Column('timeInterval', sa.Integer(), nullable=True),
    sa.Column('modeOfPlay', sa.Integer(), nullable=True),
    sa.Column('reportTime', sa.String(length=128), nullable=True),
    sa.Column('emailResponse', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('admins')
    # ### end Alembic commands ###
